Introduction callbacks
javascript-tutorial/pt.javascript.info pull request #133
Opened 2020-05-18 16:53 UTC by nildo

2020-05-18 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=133) it.</sub>

2020-12-07 17:35 UTC, odsantos commented
Hi @nildo could you please resolve the conflicts? Thank you.

2021-05-15 15:46 UTC, odsantos requested changes, later dismissed
Hi @nildo please, have you tested the code (as much as possible) as the author suggests?
Not an imperative, but having time that might be helpful.

I hope that you might let me know if you don't agree with any change.

Thank you,
Osvaldo.

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +Muitas funções providas pelo JavaScript permitem que você agende ações *assíncronas*. Em outras palavras, ações que nós iniciamos agora, mas elas terminam mais tarde.
```suggestion
Muitas funções providas pelo JavaScript permitem que você agende ações *assíncronas*. Em outras palavras, ações que nós iniciamos agora, mas elas terminam mais tarde.
```
```suggestion
Muitas funções providas pelo JavaScript permitem que você agende ações *assíncronas*. Em outras palavras, ações que nós iniciamos agora, mas que terminam mais tarde.
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
>  }
Hi, would you please translate the comments here? Thanks.

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +Mas se nós fizermos isso imediatamente depois da chamada `loadScript(…)`, não iria funcionar.
```suggestion
Mas se nós fizéssemos isso imediatamente depois da chamada `loadScript(…)`, não iria funcionar.
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz alguma coisa assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois
```suggestion
Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz alguma coisa assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois que ela terminar.
```
```suggestion
Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz alguma coisa assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois que ela estiver completa.
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +Abaixo temos uma versão melhorada do `loadScript` que pega os erros de carregamento:
```suggestion
Abaixo temos uma versão melhorada do `loadScript` que rasteia os erros de carregamento:
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +De novo, o padrão que nós usamos para o `loadScript` é bem comum. É chamado de estilo "error-first callback".
```suggestion
De novo, o padrão que nós usamos para o `loadScript` é bem comum. É chamado de estilo "callback com erro-primeiro".
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +A "pirâmide" de chamadas aninhadas cresce para a direita a cada ação assíncrona e rapidamente sai de controle.
```suggestion
A "pirâmide" de chamadas aninhadas cresce para a direita a cada ação assíncrona e rapidamente sai de controle.
```
```suggestion
A "pirâmide" de chamadas aninhadas cresce para a direita a cada ação assíncrona e rapidamente sai do controle.
```

2021-05-15 15:46 UTC, odsantos commented on 1-js/11-async/01-callbacks/article.md
> +funciona, porém o código parece uma planilha dividida. É difícil de ler, e você provavelmente percebeu que precisamos pular entre as partes do código enquanto estamos lendo ele. Isso é inconveniente,
```suggestion
Funciona, porém o código parece uma planilha dividida. É difícil de ler, e você provavelmente percebeu que precisamos de pular entre as partes do código enquanto estamos lendo ele. Isso é inconveniente, especialmente se o leitor não estiver familiarizado com o código e não souber para onde pular.
```

2022-08-06 09:07 UTC, nildo commented
/done

2022-08-13 01:23 UTC, jonnathan-ls requested changes, later dismissed
Olá nildo, segue minha revisão

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +Naturalmente, o navegador provavelmente não teve tempo de carregar o script. Então a chamada imediata para a nova função falha. Do jeito que está, a função `loadScript` não provê uma maneira de saber
**Sugestão de alteração**:

- Alterar `e eventualmente é executado` para `e é eventualmente executado`.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/35238611/184461390-bdaba7cd-85a2-42e6-8e5c-f040948e8ba8.png">

> Regra "Colocação de advérbio"
>
> https://community.languagetool.org/rule/show/COLOCA%C3%87%C3%83O_ADV%C3%89RBIO?lang=pt

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz alguma coisa assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois
**Sugestão de alteração:**

- Alterar `alguma coisa` para `algo`.
 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/35238611/184462774-6625124b-cc64-4e5f-9e0b-c9f30a211355.png">

> Regra "2. Expressões prolixas"
>
> https://community.languagetool.org/rule/show/PT_WORDINESS_REPLACE?lang=pt

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +Então, toda ação nova fica dentro de um callback. Tudo bem para poucas ações, mas não é bom para muitas ações. Por isso nós vamos ver outras variantes em breve.
**Sugestão de alteração:**

- Alterar `dentro de` para `em`.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/35238611/184462860-df26b5dd-3d9f-4e89-8b0e-4473f3419fbc.png">

> Regra "Dentro de/da(s)/do(s) > em/na(s)/no(s)"
>
> https://community.languagetool.org/rule/show/DENTRO_DE_DA_DAS_DO_DOS_EM_NA_NAS_NO_NOS?lang=pt

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +No exemplo acima nós não consideramos erros. E se o carregamento do script falhar? Nosso callback deveria ser capaz de reagir a isso.
**Sugestão de alteração:**

- Alterar `ser capaz de` para `conseguir`.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/35238611/184462959-4e4dd3d1-46b8-4033-95b1-768b6c6316e3.png">

> Regra "Ser capaz de → Conseguir"
>
> https://community.languagetool.org/rule/show/SER_CAPAZ_DE_CONSEGUIR?lang=pt

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +Então esse jeito de programar não é muito bom.
**Sugestão de alteração:**

- Alterar `muito bom` para `bom`.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/35238611/184463085-bb8bf7f9-e92f-4f42-8202-d337e70b496b.png">

> Regra "2. Expressões prolixas"
>
> https://community.languagetool.org/rule/show/PT_WORDINESS_REPLACE?lang=pt

2022-08-13 01:23 UTC, jonnathan-ls commented on 1-js/11-async/01-callbacks/article.md
> +Funciona, porém o código parece uma planilha dividida. É difícil de ler, e você provavelmente percebeu que precisamos de pular entre as partes do código enquanto estamos lendo ele. Isso é inconvenien
**Sugestão de alteração:**

- Adicionar virgula após a locução `porém`.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/35238611/184463235-fa1d7fe4-b356-4d39-8556-24969af26ac1.png">

> Regra "Locuções entre vírgulas: portanto, por exemplo, na verdade"
>
> https://community.languagetool.org/rule/show/VERB_COMMA_CONJUNCTION?lang=pt

2023-01-27 20:08 UTC, odsantos commented
Hi @nildo , the English article was updated and this PR has conflicts. Thanks.

2025-11-25 09:36 UTC, nazarepiedady commented
@gabifs

2025-11-26 17:48 UTC, gabifs commented on 1-js/11-async/01-callbacks/article.md
> +Naturalmente, o navegador provavelmente não teve tempo de carregar o script. Então a chamada imediata para a nova função falha. Do jeito que está, a função `loadScript` não provê uma maneira de saber
```suggestion
Naturalmente, o navegador provavelmente não teve tempo de carregar o script. Então a chamada imediata para a nova função falha. Do jeito que está, a função `loadScript` não provê uma maneira de saber quando o carregamento termina. O script carrega e é eventualmente executado, isso é tudo. Mas nós queremos saber quando isso acontece, para podermos usar as novas funções e variáveis daquele script.
```

2025-11-26 17:48 UTC, gabifs commented on 1-js/11-async/01-callbacks/article.md
> +Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz alguma coisa assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois
```suggestion
Isso é chamado de programação assíncrona "baseada em callbacks". A função que faz algo assincronamente deve prover um argumento `callback` onde nós colocamos a função que vai executar depois que ela estiver completa.
```

2025-11-26 17:48 UTC, gabifs commented on 1-js/11-async/01-callbacks/article.md
> +Então, toda ação nova fica dentro de um callback. Tudo bem para poucas ações, mas não é bom para muitas ações. Por isso nós vamos ver outras variantes em breve.
```suggestion
Então, toda ação nova fica em um callback. Tudo bem para poucas ações, mas não é bom para muitas ações. Por isso nós vamos ver outras variantes em breve.
```

2025-11-26 17:48 UTC, gabifs commented on 1-js/11-async/01-callbacks/article.md
> +Funciona, porém o código parece uma planilha dividida. É difícil de ler, e você provavelmente percebeu que precisamos de pular entre as partes do código enquanto estamos lendo ele. Isso é inconvenien
```suggestion
Funciona, porém, o código parece uma planilha dividida. É difícil de ler, e você provavelmente percebeu que precisamos de pular entre as partes do código enquanto estamos lendo ele. Isso é inconveniente, especialmente se o leitor não estiver familiarizado com o código e não souber para onde pular.
```

2025-11-26 17:50 UTC, gabifs approved these changes
LGTM!

2025-11-26 22:46 UTC, gabifs commented
@nazarepiedady I had to resolve conflicts here, could you please review it?

2025-11-27 09:24 UTC, nazarepiedady approved these changes
It is good for now, let's go ahead with these translations. @gabifs

2025-11-27 09:26 UTC, merged