Character classes
javascript-tutorial/pt.javascript.info pull request #143
Opened 2020-05-25 22:27 UTC by fsdude

Specified changes in commits.
Just following english version: https://github.com/javascript-tutorial/en.javascript.info/tree/master/9-regular-expressions/02-regexp-character-classes

2020-12-08 19:03 UTC, odsantos commented
Hi @fsdude would you please also resolve the conflicts, or kindly inform if unavailable to? Thank you.

2020-12-09 23:15 UTC, fsdude commented
> Hi @fsdude would you please also resolve the conflicts, or kindly inform if unavailable to? Thank you.

Hello! Yeah.. lately I've been busy with some work. I don't know if I'll be able to fix this soon, sorry for that
Thanks by the way =)

2020-12-09 23:20 UTC, odsantos commented
@fsdude Thank you.

2020-12-24 23:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=143) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=143) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: odsantos<br/>:white_check_mark: joaquinelio<br/>:white_check_mark: iliakan<br/>:x: heypano<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=143) it.</sub>

2021-05-17 10:53 UTC, odsantos requested changes
Hi @kiniggit, @luizclr, @adriavieira314, @Mr-Saxobeat, please since @fsdude might be unavailable I would appreciate if any of you could review this PR #143 , including my revision.
Thank you.

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Considere uma tarefa prática - temos um número de telefone como `"+7(903)-123-45-67"` e precisamos transformá-lo em números puros: `79031234567`.
```suggestion
Considere uma tarefa prática - temos um número de telefone como `"+7(903)-123-45-67"` e precisamos transformá-lo em números apenas: `79031234567`.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +: Um símbolo de espaço: inclui espaços, tabulações `\t`, novas linhas `\n` e alguns outros caracteres raros, como `\v`, `\f` and `\r`.
```suggestion
: Um símbolo de espaço: inclui espaços, tabulações `\t`, novas linhas `\n` e alguns outros caracteres raros, como `\v`, `\f` e `\r`.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +`padrão:\w` ("w" é de "word")
```suggestion
`padrão:\w` ("w" é de "word" (*palavra*))
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Por exemplo, `padrão:CSS\d` corresponde a uma string `correspondência:CSS` com um dígito após:
```suggestion
Por exemplo, `padrão:CSS\d` corresponde a uma string `correspondência:CSS` com um dígito a seguir:
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Para cada classe de caractere existe uma "classe inversa", denotada com a mesma letra, mas em maiúsculas.
```suggestion
Para cada classe de caracteres existe uma "classe inversa", denotada com a mesma letra, mas em maiúsculas.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +: Sem dígito: qualquer caractere, exceto `padrão:\d`, por exemplo, uma letra.
```suggestion
: Não-dígito: qualquer caractere, exceto `padrão:\d`, por exemplo, uma letra.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +: Sem espaço: qualquer caractere, exceto `padrão:\s`, por exemplo, uma letra.
```suggestion
: Não-espaço: qualquer caractere, exceto `padrão:\s`, por exemplo, uma letra.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +No início do capítulo, vimos como criar um número de telefone somente para números a partir de uma string como `subject:+7(903)-123-45-67`: encontre todos os dígitos e junte-se a eles.
```suggestion
No início do capítulo, vimos como criar um número de telefone somente com números a partir de uma string como `subject:+7(903)-123-45-67`: encontre todos os dígitos e os junte.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Uma maneira alternativa e mais curta é encontrar um `padrão:\D` não-dígito e removê-lo da string:
```suggestion
Uma maneira alternativa e mais curta é encontrar não-dígitos com `padrão:\D` e removê-los da string:
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Um ponto `padrão:.` é uma classe de caractere especial que corresponde a "qualquer caractere, exceto uma nova linha".
```suggestion
Um ponto `padrão:.` é uma classe de caracteres especial que corresponde a "qualquer caractere, exceto uma nova linha".
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Por exemplo, a regexp `padrão:A.B` corresponde `corresponde:A` e, em seguida, `corresponde:B` com qualquer caractere entre eles, exceto uma nova linha `\n`:
```suggestion
Por exemplo, a regexp `padrão:A.B` corresponde a `correspondência:A` e, em seguida, `correspondência:B` com qualquer caractere entre eles, exceto uma nova linha `\n`:
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +É o que flag `padrão:s` faz. Se uma regexp possui, então um ponto `padrão:.` corresponde literalmente a qualquer caractere:
```suggestion
É o que flag `padrão:s` faz. Se uma regexp a possui, então um ponto `padrão:.` corresponde literalmente a qualquer caractere:
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +### Ponto como literalmente qualquer caractere com a flag "s"
```suggestion
### Ponto, como literalmente qualquer caractere, com a flag "s"
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +````warn header="Não suportado no Firefox, IE, Edge"
```suggestion
````warn header="Não suportado no Firefox, IE, Edge"
```
```suggestion
````warn header="Não suportado no IE"
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Verifique <https://caniuse.com/#search=dotall> para obter o estado de suporte mais recente. No momento da redação deste documento, não inclui o Firefox, IE, Edge.
```suggestion
A flag `padrão:s` não é suportada no IE.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Felizmente, há uma alternativa, que funciona em qualquer lugar. Podemos usar uma regexp como `padrão:[\s\S]` para corresponder a "qualquer caractere".
```suggestion
Felizmente, há uma alternativa, que funciona em qualquer lugar. Podemos usar uma regexp como `padrão:[\s\S]` para corresponder a "qualquer caractere" (este padrão será estudado no artigo <info:regexp-character-sets-and-ranges>).
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +O padrão `padrão:[\s\S]` diz literalmente: "um caractere de espaço OU não um caractere de espaço". Em outras palavras, "qualquer coisa". Poderíamos usar outro par de classes complementares, como `pad
```suggestion
O padrão `padrão:[\s\S]` diz literalmente: "um caractere de espaço OU não um caractere de espaço". Em outras palavras, "qualquer coisa". Poderíamos usar outro par de classes complementares, como `padrão:[\d\D]`, não importa. Ou mesmo o padrão `padrão:[^]` - pois significa corresponder a qualquer caractere, exceto nada.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Também podemos usar esse truque se quisermos os dois tipos de "pontos" no mesmo padrão: o ponto real `padrão:.` comportando-se da maneira regular ("não incluindo uma nova linha") e também uma maneira
```suggestion
Também podemos usar esse truque se quisermos os dois tipos de "pontos" no mesmo padrão: o ponto real `padrão:.` comportando-se da maneira regular ("não incluindo uma nova linha") e também uma maneira de combinar "qualquer caractere" com `padrão:[\s\S]` ou similar.
```
```suggestion
Também podemos usar esse truque se quisermos os dois tipos de "pontos" no mesmo padrão: o real ponto `padrão:.` comportando-se da maneira regular ("não incluindo uma nova linha") e também uma maneira de combinar "qualquer caractere" com `padrão:[\s\S]` ou similar.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +````warn header="Preste atenção nos espaços"
```suggestion
````warn header="Preste atenção aos espaços"
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Vamos corrigi-lo adicionando espaços ao padrão regexp `padrão:\d - \d`:
```suggestion
Vamos corrigir adicionando espaços ao padrão regexp `padrão:\d - \d`:
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +**Um espaço é um caractere. Igual em importância com qualquer outro caractere.**
```suggestion
**Um espaço é um caractere. Igual em importância a qualquer outro caractere.**
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Não podemos adicionar ou remover espaços de uma expressão regular e esperamos funcionar da mesma maneira.
```suggestion
Não podemos adicionar ou remover espaços de uma expressão regular e esperar que funcione da mesma maneira.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +- `padrão:\D` - sem dígitos.
```suggestion
- `padrão:\D` - sem dígitos.
```
```suggestion
- `padrão:\D` - não-dígitos.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +- `padrão:.` - qualquer caractere se estiver com a flag regexp `'s' `; caso contrário, qualquer um, exceto uma nova linha `\n`.
```suggestion
- `padrão:.` - qualquer caractere se estiver com a flag regexp `'s' `;, caso contrário, qualquer um exceto uma nova linha `\n`.
```

2021-05-17 10:53 UTC, odsantos commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +A codificação unicode, usada pelo JavaScript para strings, fornece muitas propriedades para caracteres, como: a qual idioma a letra pertence (se é uma letra), é um sinal de pontuação etc.
```suggestion
A codificação unicode, usada pelo JavaScript para strings, fornece muitas propriedades para caracteres, como: a qual idioma a letra pertence (se for uma letra), é um sinal de pontuação etc.
```

2021-07-14 19:32 UTC, odsantos reviewed
Since @fsdude is not available, I applied the changes and will wait for another reviewer.

2023-01-23 21:24 UTC, closed without merging