Patterns and flags
javascript-tutorial/pt.javascript.info pull request #147
Opened 2020-05-28 00:04 UTC by fsdude

Retranslation done. I removed 'article-pt.md' file too, just to keep the quantity of files same as the english.

2021-05-18 15:25 UTC, odsantos requested changes
Hi @kiniggit, @luizclr, @adriavieira314, @Mr-Saxobeat, please since @fsdude might be unavailable I would appreciate if any of you could review this PR #147 , including my revision.
Thank you.

2021-05-18 15:25 UTC, odsantos commented on 9-regular-expressions/01-regexp-introduction/article.md
> +3. E, finalmente, se não houver correspondências, `null` é retornado (não importa se há flags `padrão:g` ou não).
```suggestion
3. E, finalmente, se não houver correspondências, `null` é retornado (não importa se há a flag `padrão:g` ou não).
```

2021-05-18 15:25 UTC, odsantos commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- Uma expressão regular consiste em um padrão e opcionais flags: `padrão:g`, `padrão:i`, `padrão:m`, `padrão:u`, `padrão:s`, `padrão:y`.
```suggestion
- Uma expressão regular consiste em um padrão e flags opcionais: `padrão:g`, `padrão:i`, `padrão:m`, `padrão:u`, `padrão:s`, `padrão:y`.
```

2021-05-18 15:25 UTC, odsantos commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- O método `str.replace(regexp, substituição)` substitui as correspondências encontradas usando `regexp` por `replace`: todas elas se houver uma flag `padrão:g`, caso contrário, somente a primeira.
```suggestion
- O método `str.replace(regexp, substituição)` substitui as correspondências encontradas usando `regexp` por 'substituição': todas elas se houver uma flag `padrão:g`, caso contrário, somente a primeira.
```

2021-07-14 19:40 UTC, odsantos reviewed
Sine @fsdude is not available, I applied my own changes and will wait for another reviewer.

2022-12-13 20:59 UTC, odsantos commented
Hi  @luizclr, @jonnathan-ls , @Mr-Saxobeat,  since @fsdude might be unavailable I would appreciate if any of you could review this PR https://github.com/javascript-tutorial/pt.javascript.info/pull/147.
Thank you.

2023-01-22 21:49 UTC, odsantos commented
Hi @luizclr , @Mr-Saxobeat , @jonnathan-ls , anyone available for reviewing this PR #147 ? Thanks.

2024-01-17 03:04 UTC, Peruibeloko commented
@jonnathan-ls @odsantos esse PR também apresenta o mesmo problema da tradução do `pattern:`

2024-01-17 22:48 UTC, odsantos commented
@Peruibeloko would you please check [this](https://github.com/javascript-tutorial/pt.javascript.info/pull/141#issuecomment-1897178315) comment? Thanks.

2024-01-20 22:54 UTC, jonnathan-ls approved these changes
LGTM 

Eu apliquei as atualizações de trechos que não devem ser traduzidos, conforme commit https://github.com/javascript-tutorial/pt.javascript.info/pull/147/commits/91686e7bccba28e4b8e5da623ae28223388aecfa

2024-01-20 22:56 UTC, jonnathan-ls commented
> ... esse PR também apresenta o mesmo problema da tradução do `pattern:`

Grato pela observação ❤️, eu apliquei o ajuste no último commit e na aprovação que deixei https://github.com/javascript-tutorial/pt.javascript.info/commit/91686e7bccba28e4b8e5da623ae28223388aecfa

2024-01-20 23:04 UTC, jonnathan-ls commented
> Hi ... anyone available for reviewing this PR #147 ? Thanks.

@odsantos eu adicionei minha aprovação e a observação que o Peruibeloko registrou de textos que não devem ser traduzidos.

Como você já tinha registrado sua revisão e realizou os ajustes necessários, por gentileza, registrar a aprovação de suas solicitações, para o BOT deste repositório conseguir observar e o status do PR estar condizente na marcação da lista de tarefas (issue 01). 

Para registrar a aprovação de sua revisão, basta clicar nos três pontinhos de menu e atualizar com sua aprovação, para que possamos prosseguir com o Merge Request.

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/4f217fbd-76a8-49ee-817c-9a5c8ee2fea9)

2024-03-10 05:22 UTC, nazarepiedady approved these changes
It seems good enough to be approved, so I do it.

2024-03-10 05:24 UTC, merged