Translated article "Type Conversion"
javascript-tutorial/pt.javascript.info pull request #212
Opened 2021-02-28 19:03 UTC by PauloBacelar

2021-02-28 19:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=212) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=212) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=212) it.</sub>

2021-07-16 09:04 UTC, odsantos commented
Hi @PauloBacelar , this topic is assigned to @mrodrigochaves .
Did you translate the whole article? Thank you.

2021-07-16 10:06 UTC, PauloBacelar commented
> Hi @PauloBacelar , this topic is assigned to @mrodrigochaves .
> Did you translate the whole article? Thank you.

Hello, @odsantos.

The article is fully translated. When I translated it, I didn't know about the existence of [this issue](https://github.com/javascript-tutorial/pt.javascript.info/issues/1), so I didn't assign the task to myself. 

If @mrodrigochaves translated, you can use his translation. Otherwise, feel free to use mine. When I get some free time I'll translate some other articles.

2021-07-16 14:13 UTC, odsantos commented
Hi @PauloBacelar , if I do not get a response from @mrodrigochaves in a couple of days I'll assign this topic to you, and then if you don't mind I'll ask you to add his translations to yours since he already translated two files on a subfolder.

Thank you.

2021-07-19 19:56 UTC, odsantos requested changes
Hi @PauloBacelar,

Here is my review. Please, feel free to comment where you disagree.
Thank you.

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Podemos usar a função Number(`valor`) para converter `valor` para number.
```suggestion
Podemos usar a função Number(`value) para converter `value` para number.
```
(Variable not translated.)

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert( "6" / "2" ); // 3, strings viram numbers
```suggestion
alert( "6" / "2" ); // 3, strings viram números
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +let num = Number(str); // vira um number: 123
```suggestion
let num = Number(str); // vira o número 123
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Conversões explícitas geralmente são obrigatórias quando estamos obtendo um valor de uma fonte baseada em string - como um texto - mas esperamos um receber um valor numérico.
```suggestion
Conversões explícitas geralmente são obrigatórias quando estamos a ler um valor de uma fonte baseada em string - como um texto - mas esperamos receber um valor numérico.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +let age = Number("uma string ao invés de um number");
```suggestion
let age = Number("uma string ao invés de um número");
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert(age); // NaN, conversão falhou
```suggestion
alert(age); // NaN, a conversão falhou
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +|`true` e `false` | `1` e `0` |
```suggestion
|<code>true&nbsp;e&nbsp;false</code>| `1` e `0` |
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +alert( Number("123z") );      // NaN (Erro ao ler "z")
```suggestion
alert( Number("123z") );      // NaN (Erro ao ler um número em "z")
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +A maioria dos operadores matemáticos também performam essa conversão, na qual veremos no próximo capítulo.
```suggestion
A maioria dos operadores matemáticos também executam essa conversão, o que veremos no próximo capítulo.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Acontecem em uma operação lógica (depois veremos testes de condição e outras coisas similares), mas também podem acontecer explicitamente ao usar a função `Boolean(valor)`.
```suggestion
Acontecem em operações lógicas (depois veremos testes de condição e outras coisas similares), mas também podem acontecer explicitamente ao usar a função `Boolean(value)`.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Algumas linguagens de programação (isto é, PHP), tratam `\"0\"` como `false`. Mas no JavaScript, uma string não-vazia sempre é `true`.
```suggestion
Algumas linguagens de programação (como PHP), tratam `\"0\"` como `false`. Mas no JavaScript, uma string não-vazia sempre é `true`.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversões para String`** -- Ocorrem quando mostramos algum valor. Podem ser explicitamente feitas com `String(valor)`. As conversões para string geralmente é obvia em tipos primitivos.
```suggestion
**`Conversões para String`** -- Ocorrem quando mostramos algum valor. Podem ser explicitamente feitas com `String(value)`. As conversões para string geralmente são óbvias com tipos primitivos.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversões Numéricas`** -- Ocorrem em operações matemáticas. Podem ser feitas com `Number(valor)`.
```suggestion
**`Conversões Numéricas`** -- Ocorrem em operações matemáticas. Podem ser feitas com `Number(value)`.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +|`true` e `false` | `1` e `0` |
```suggestion
|<code>true&nbsp;/&nbsp;false</code>| `1 / 0` |
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +| `string` | Espaços em branco do início e do fim são removidos. Se a string que sobrar for vazia, o resultado é `0`. Senão, o número é "lido" a partir da string. Um erro nos dá `NaN`|
```suggestion
| `string` | A string é lida "como ela é", espaços em branco do início e do fim são ignorados. Uma string vazia, vira `0`. Um erro nos dá `NaN`|
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +**`Conversões Booleanas`** -- Ocorrem em operações lógicas. Podem ser feitas com `Boolean(valor)`.
```suggestion
**`Conversões Booleanas`** -- Ocorrem em operações lógicas. Podem ser feitas com `Boolean(value)`.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +- `Number(undefined)` vira `NaN`, não `0`.
```suggestion
- `undefined` é `NaN` como número, não `0`.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +- `"0"` e strings só com espaço `"   "` são `true` como booleanos.
```suggestion
- `"0"` e strings só com espaços `"   "` são `true` como booleanos.
```

2021-07-19 19:56 UTC, odsantos commented on 1-js/02-first-steps/07-type-conversions/article.md
> +Objetos não são citados aqui. Retornaremos depois no capítulo <info:object-toprimitive> que é dedicado exclusivamente para objetos, após aprendermos coisas mais básicas de JavaScript.
```suggestion
Objetos não são citados aqui. Retornaremos depois no capítulo <info:object-toprimitive> que é dedicado exclusivamente a objetos, após aprendermos coisas mais básicas de JavaScript.
```

2021-07-19 20:24 UTC, PauloBacelar commented
> Hi @PauloBacelar,
> 
> Here is my review. Please, feel free to comment where you disagree.
> Thank you.

Thanks for reviewing. Tomorrow I'll commit your changes to the file

2021-07-19 20:33 UTC, odsantos commented
> > Hi @PauloBacelar,
> > Here is my review. Please, feel free to comment where you disagree.
> > Thank you.
> 
> Thanks for reviewing. Tomorrow I'll commit your changes to the file

Thank you.

2021-07-20 14:11 UTC, PauloBacelar commented
/done

2021-07-20 14:28 UTC, odsantos approved these changes
Hi @PauloBacelar, 

Following the rules, we now need a second maintainer to review your translation.

Thank you.

2022-06-20 00:05 UTC, jonnathan-ls commented
@PauloBacelar 

Great translation ❤️

@odsantos 

I'm reading each article on the platform to evolve with the translation to the PT language and terms the url with published subdomain, as it exists in other languages ​​already fully translated: see https://github.com/javascript-tutorial/pt.javascript.info/issues/1#issuecomment-1151946827 in the [progress edit](https://github.com/javascript-tutorial/pt.javascript.info/issues/1).

Considering that the translation of this article contemplates this open PR, I would like to know if I have permission here to leave my review note or if I can contribute in some other way to the evolution of this edition?

> This PR has been open for over 1 year.

From the translation, I identified two points of correction (as previously commented)

2022-06-24 02:05 UTC, jonnathan-ls requested changes
Hello [PauloBacelar](https://github.com/PauloBacelar)

Could you correct the quoted comments, please?

2022-06-29 02:17 UTC, jonnathan-ls approved these changes

2022-06-29 02:19 UTC, merged

2022-06-29 02:24 UTC, jonnathan-ls commented
@PauloBacelar ... we appreciate the collaboration ⭐