Translate the page to Portuguese
javascript-tutorial/pt.javascript.info pull request #213
Opened 2021-03-10 12:07 UTC by alexregado

I didn't translate the words node and child because in Portuguese they cannot be translated to the original meaning. Happy to Help :)

2021-03-10 12:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=213) it.</sub>

2021-07-14 20:11 UTC, odsantos requested changes
Hello @alexregado,

Here is my review.
Please feel free to comment where you disagree.

Would you also first pick the corresponding topic you're translating [here](https://github.com/javascript-tutorial/pt.javascript.info/issues/1),  and then change "Translate the page to Portuguese" to the title of that topic?

Thank you,
Osvaldo.

2021-07-14 20:11 UTC, odsantos commented on 2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
> +// Obtém o <ul>, e depois seleciona o último child element
```suggestion
// Obtém o <ul>, e depois seleciona o último elemento descendente
```

2021-07-16 10:12 UTC, odsantos commented
Hi @alexregado , I dismissed my review.
This topic is already assigned to @exploitmik .
Would you please choose an assigned topic?
Thank you.

2021-07-23 02:05 UTC, jjuliomarttins approved these changes

2021-07-23 15:32 UTC, odsantos commented
Hi @jjuliomarttins please do not approve pull requests.
Only maintainers should review and approve them. 

This article is assigned to another person, so as such it shouldn't even be approved unless the other person seemed unavailable.
Thank you.

2024-03-10 05:02 UTC, nazarepiedady commented
@Peruibeloko, @jonnathan-ls, @odsantos, do you consider it a good idea to close this pull request?

2024-03-23 21:23 UTC, Peruibeloko commented
@nazarepiedady lets close this one as well

2024-10-13 13:56 UTC, closed without merging