Scripts: async, defer
javascript-tutorial/pt.javascript.info pull request #229
Opened 2021-10-23 03:08 UTC by larissaiurk

2022-12-11 21:40 UTC, odsantos commented
Hi @larissaiurk,

Still available for this task?
There is a conflict here.

Please, let me know if you have not time, and I might be able to resolve it.

Thanks,
Osvaldo.

2024-03-01 20:05 UTC, nazarepiedady commented
@Peruibeloko, @jonnathan-ls, do you have time to see what is possible to do in relation to this pull request?

2024-03-06 08:16 UTC, nazarepiedady commented
@Peruibeloko, could you help to fix the conflicts?

2024-03-17 18:14 UTC, jonnathan-ls approved these changes
LGTM

Adicionei ajustes simples (0dfdf2503ca1d5d7b82e0514af1dcc6bb21c68bc) e resolvi o conflito de merge (b0b6ae0ba95c5df71fb4e838ebe1056f5e6f0d71)

2024-03-17 18:18 UTC, jonnathan-ls commented
> ... could you help to fix the conflicts, update, and approve it?

During the review, I added simple adjustments (including the suggestion requested by @Peruibeloko) and also conflict resolution @nazarepiedady

2024-03-17 18:19 UTC, jonnathan-ls commented on 2-ui/5-loading/02-script-async-defer/article.md
> +2. Se houver um script volumoso no topo da página, ele vai "bloqueia a página". Os usuários não podem ver o conteúdo da página até que ele faça o download e execute:
Ajustado

2024-03-17 18:49 UTC, nazarepiedady requested changes
It is good, but there are some little changes needed.

2024-03-17 18:49 UTC, nazarepiedady commented on 2-ui/5-loading/02-script-async-defer/article.md
> +## Dynamic scripts
It was not translated yet.

2024-03-17 18:49 UTC, nazarepiedady commented on 2-ui/5-loading/02-script-async-defer/article.md
> +There's one more important way of adding a script to the page.
It also was not translated yet.

2024-03-17 18:51 UTC, nazarepiedady commented
@jonnathan-ls, there are some changes that need to be translated.

2024-03-17 18:57 UTC, jonnathan-ls commented on 2-ui/5-loading/02-script-async-defer/article.md
> +## Dynamic scripts
Done

2024-03-17 18:57 UTC, jonnathan-ls commented on 2-ui/5-loading/02-script-async-defer/article.md
> +There's one more important way of adding a script to the page.
Done

2024-03-17 18:58 UTC, jonnathan-ls commented
@nazarepiedady Thanks for watching, pending translation added

/done

2024-03-17 19:03 UTC, nazarepiedady approved these changes
It is good to be applied.

2024-03-17 19:05 UTC, merged