Prototypal inheritance
javascript-tutorial/pt.javascript.info pull request #230
Opened 2021-10-24 19:06 UTC by flaviohblima

Prototypal inheritance

2021-12-20 23:16 UTC, odsantos requested changes
Hello @flaviohblima ,

Here is a review.
Please, feel free to leave a note where you might disagree.

Thank you,
Osvaldo.

2021-12-20 23:16 UTC, odsantos commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Quase todas as outras chaves/métodos *value-gettting*, como `Object.keys`, `Object.values`, entre outros, ignoram propriedades herdadas.
```suggestion
Quase todas as outras chaves/métodos *obtém-valor*, como `Object.keys`, `Object.values`, entre outros, ignoram propriedades herdadas.
```

2021-12-20 23:16 UTC, odsantos commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +- Nós podemos usar `obj.__proto__` para acessá-lo (um getter/setter que é histórico, para o qual já temos alternativas, que veremos em breve).
```suggestion
- Nós podemos usar `obj.__proto__` para acessá-lo (um histórico getter/setter, mas já existem alternativas, que veremos em breve).
```

2021-12-20 23:16 UTC, odsantos commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +- Operações de escrever/deletar agem diretamente no objeto, elas não usam o protótipo (assumindo que a propriedade seja um dado, não um setter).
```suggestion
- Operações de escrever/deletar agem diretamente no objeto, elas não usam o protótipo (assumindo que seja uma propriedade para dados, não um setter).
```

2021-12-20 23:16 UTC, odsantos commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +- O loop `for..in` itera tanto sobre as propriedades do objeto quanto sobre as propriedades herdadas. Todas as outras chaves/métodos *value-getting* operam apenas sobre o próprio objeto.
```suggestion
- O loop `for..in` itera tanto sobre as propriedades do objeto quanto sobre as propriedades herdadas. Todas os outros métodos  para obter chaves/valores operam apenas sobre o próprio objeto.
```

2022-02-26 23:31 UTC, flaviohblima commented
/done

2022-12-11 21:35 UTC, odsantos commented
Hi @flaviohblima ,

Still working in this one?
There is a conflict here.

Please, let me know if you haven't time and I might be able to resolve it.

Thanks,
Osvaldo.

2022-12-13 13:51 UTC, flaviohblima commented
Hi @odsantos ,

Sorry I could not resolve this pull request.
I might work in some translations soon.

In any case, feel free to resolve the conflicts and close it.

Team work is always quickier!

Thank you,
Flávio.

2022-12-23 19:48 UTC, odsantos commented
Hi @flaviohblima ,

I'll try to resolve the conflicts but keep it open.
Probably, it can be reviewed by others maintainers, as well, and get merged.

Thank you,
Osvaldo.

2024-03-01 20:06 UTC, nazarepiedady commented
@Peruibeloko, @jonnathan-ls, do you have time to see what is possible to do in relation to this pull request?

2024-03-06 00:38 UTC, Peruibeloko requested changes
Parece bastante coisa, mas na verdade são só alterações pequenas e pedidos de tradução do código.

Acredito que seja importante traduzir os nomes usados nos exemplos do artigo, já que o tópico pode ser de difícil compreensão para iniciantes

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Na programação, nós sempre queremos extender algum comportamento.
```suggestion
Na programação, é comum querermos extender algum comportamento.
```

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
> +3. `undefined`, essa propriedade não existe mais.
```suggestion
1. `true`, obtido de `coelho`.
2. `null`, obtido de `animal`.
3. `undefined`, essa propriedade não existe mais.
```

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
Traduzir as variáveis

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
Traduzir as variáveis

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Por exemplo, nós temos um objeto `user` com suas propriedades e métodos, e queremos criar duas variantes `admin` e `guest` ligeiramente diferentes. Nós gostaríamos de reutilizar o que já temos no `us
```suggestion
Por exemplo, nós temos um objeto `usuario` com suas propriedades e métodos, e queremos criar duas variantes `admin` e `convidado` ligeiramente diferentes. Nós gostaríamos de reutilizar o que já temos no `usuario`, sem copiar/reimplementar seus métodos, apenas construir um novo objeto baseado nele.
```

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  ```js run
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +1. As referências não podem ser circulares. O Javascript vai disparar um erro caso a gente tente atribuir `__proto__` em um círculo de objetos.
```suggestion
1. As referências não podem ser circulares. O Javascript vai disparar um erro caso a gente tente atribuir `__proto__` ao seu próprio objeto, ou ao objeto que o utiliza, de maneira recursiva.
```

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  ```js run
Traduzir o restante do código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  ```js run
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  ```js run
Traduzir o resto do código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
>  ```js run
Traduzir o código

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +```smart header="Quase todas as outras chaves/métodos *obtém-valor* ignoram propriedades herdadas."
```suggestion
```smart header="Quase todos os métodos que obtém valores a partir de chaves ignoram propriedades herdadas."
```

2024-03-06 00:38 UTC, Peruibeloko commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +- Nós podemos usar `obj.__proto__` para acessá-lo (um histórico getter/setter, mas já existem alternativas, que veremos em breve).
```suggestion
- Nós podemos usar `obj.__proto__` para acessá-lo (um getter/setter mantido historicamente, mas já existem alternativas, que veremos em breve).
```

2024-03-06 08:13 UTC, nazarepiedady commented
@Peruibeloko, I was talking about to edit this pull request and approved if possible.

2024-03-06 14:52 UTC, Peruibeloko commented
@nazarepiedady I believe the repo is write protected, but it I'll see what I can do

2024-11-01 23:33 UTC, Peruibeloko approved these changes

2024-11-02 06:30 UTC, nazarepiedady approved these changes

2024-11-02 06:32 UTC, merged