F.prototype
javascript-tutorial/pt.javascript.info pull request #231
Opened 2021-10-25 02:55 UTC by flaviohblima

2021-10-29 20:14 UTC, flaviohblima commented
Hello @odsantos ,

I missed some of your reviews in my last reading. Sorry.

Now I think I resolved everything.

I did not resolve [this one](https://github.com/javascript-tutorial/pt.javascript.info/pull/231#discussion_r736879429), because I do not use the "de" like this.

If its ok for you, I believe now its done.

Thank you for your reviews!
Flávio

2021-10-29 20:28 UTC, odsantos commented
Hello @flaviohblima , 
Thank you for your message.

I hope to check it as soon as possible. Probably, within a few days.

However, I still see my review notes. I believe I shouldn't if they were resolved and committed.
But it might be all right, as well.

Osvaldo.

2021-10-31 22:52 UTC, odsantos requested changes
Hello @flaviohblima ,

Here is another review.

Thank you,
Osvaldo.

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +Nós podemos usar essa abordagem se nós temos certeza que a propriedade `"constructor"` tem o valor correto.
```suggestion
Nós podemos usar essa abordagem se nós tivermos a certeza de que a propriedade `"constructor"` tem o valor correto.
```

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +Por exemplo, se nós não tocarmos o `"prototype"` padrão, então esse código funciona com certeza:
```suggestion
Por exemplo, se nós não tocarmos no `"prototype"` padrão, então esse código funciona com certeza:
```

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +Por exemplo, se nós não tocarmos o `"prototype"` padrão, então esse código funciona com certeza:
```suggestion
Por exemplo, se nós não tocarmos no `"prototype"` padrão, então esse código funciona com certeza:
```

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +...Mas se alguém, por acaso, sobrescrever `User.prototype` e esquecer de recriar o `constructor` com referência ao próprio `User`, então o código iria falhar.
```suggestion
...Mas se alguém, por acaso, sobrescrever `User.prototype` e se esquecer de recriar o `constructor` referenciando `User`, então o código irá falhar.
```

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +2. Depois, ele segue a cadeia de protótipos. O protótipo de `user` é `User.prototype`, e ele também não tem um `constructor` (porque nós "esquecemos" de configurá-lo!).
```suggestion
2. Depois, ele segue a cadeia de protótipos. O protótipo de `user` é `User.prototype`, e ele também não tem um `constructor` (porque nós nos "esquecemos" de configurá-lo!).
```

2021-10-31 22:52 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/article.md
> +Note que o `F.prototype` aqui significa uma propriedade regular de nome `"prototype"` dentro de `F`. Isso soa um pouco similar ao termo "prototype" (protótipo), mas aqui nós estamos falando realmente
```suggestion
Note que o `F.prototype` aqui significa uma propriedade regular chamada `"prototype"` dentro de `F`. Isso soa um pouco similar ao termo "prototype" (protótipo), mas aqui nós estamos falando realmente de uma propriedade regular com esse nome.
```

2021-11-01 16:44 UTC, flaviohblima commented
/done

2021-11-19 20:53 UTC, odsantos requested changes
Hello @flaviohblima ,

I reopened a conversation and I still am insisting on that one with 'de'.
Would you mind if I ask you to review it again?
Please, I continue open to your appreciation of my review.

Thank you,
Osvaldo.

2021-11-19 20:53 UTC, odsantos commented on 1-js/08-prototypes/02-function-prototype/article.md
> +Isso é prático quando nós temos um objeto, não sabemos qual construtor foi usado para ele (de uma biblioteca de terceiros, por exemplo), e nós precisamos criar outro objeto do mesmo tipo.
Hello @flaviohblima,

I believe you told me you do not use 'de' here but could you review this excerpt?

Thank you.

2021-11-24 14:37 UTC, flaviohblima commented
Hello @odsantos ,

If you insist, I see no problem fixing it. I already commited the change.

Thank you,
Flávio

2021-11-24 14:37 UTC, flaviohblima commented
/done

2021-11-28 21:19 UTC, odsantos approved these changes
Hello @flaviohblima ,

I appreciate the patience you had.
By the rules, we need a  second reviewer for your work to be merged.

Let's hope that either @luizclr, @Mr-Saxobeat, @adriavieira314, or @kiniggit have time for that.

Best regards,
Osvaldo.

2022-04-29 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=231) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=231) it.</sub>

2022-07-06 04:35 UTC, jonnathan-ls requested changes
@flaviohblima 

> I recorded some notes

**Note**: the images (SVG) have not been translated.

I didn't add the above note in the review, but I was wondering if you could perform the script translation procedure? As per image translation guidance at https://github.com/javascript-tutorial/server#translating-images

If not, **no problem**, I perform the procedure separately in another Pull Request.

2022-07-06 04:35 UTC, jonnathan-ls commented on 1-js/08-prototypes/02-function-prototype/article.md
> +Por definição, todas as funções possuem `F.prototype = { constructor: F }`, então nós podemos obter o construtor de um objeto acessando sua propriedade `"constructor"`.
> Expressões prolixas - [PT_WORDINESS_REPLACE](https://community.languagetool.org/rule/show/PT_WORDINESS_REPLACE?lang=pt)

- `Por definição` is a long-winded expression.
- Suggestion: change to `Por padrão`

<img width="671" alt="image" src="https://user-images.githubusercontent.com/35238611/177465244-afdc1a98-1673-40e0-8ea6-db202aebe226.png">

2022-07-06 04:35 UTC, jonnathan-ls commented on 1-js/08-prototypes/02-function-prototype/article.md
> +Nós podemos usar a propriedade `constructor` para criar um novo objeto usando o próprio construtor de um objeto que já exista.
> **Pleonasmo** - [REDUNDANCY_CRIAR](https://community.languagetool.org/rule/show/REDUNDANCY_CRIAR?lang=pt)

- The term "create" already refers to the meaning of "new"
- This way, there is no need for the word "new"
- Change suggestion: `criar um novo` by `criar um`

<img width="380" alt="image" src="https://user-images.githubusercontent.com/35238611/177464847-ffeef3cc-1f8f-4e3e-bef8-ff688d92974b.png">

2022-07-06 04:35 UTC, jonnathan-ls commented on 1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
> +(Caso você esteja curioso, a chamada `new Object(...)` converte o seu argumento para um objeto. Isso é algo teórico, mas na prática ninguém faz a chamada `new Object` com um valor, e geralmente nós n
> Locuções entre vírgulas: portanto, por exemplo, na verdade [VERB_COMMA_CONJUNCTION](https://community.languagetool.org/rule/show/VERB_COMMA_CONJUNCTION?lang=pt)

- This phrase must be separated by commas, and must only be used at the beginning of a sentence for stylistic purposes. **Change suggestion**: `mas, na prática,`

<img width="674" alt="image" src="https://user-images.githubusercontent.com/35238611/177466351-f553130d-1aab-4829-879b-b6eeeb07d72f.png">

2022-07-06 04:35 UTC, jonnathan-ls commented on 1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
> +    Objetos são atrbuídos por referência. O objeto do `Rabbit.prototype` não é duplicado, ele continua sendo um único objeto referenciado por `Rabbit.prototype` e pelo `[[Prototype]]` do `rabbit`.
> Grammatical Error

- Change `atrbuídos` to `atribuídos`

<img width="270" alt="image" src="https://user-images.githubusercontent.com/35238611/177467856-d8d67272-cd32-40ad-b8a8-923f0a9ed34a.png">

2022-07-06 04:35 UTC, jonnathan-ls commented on 1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
> +3. E se for assim (a linha foi substituída)?
> Frases seguidas começadas com a mesma palavra [PORTUGUESE_WORD_REPEAT_BEGINNING_RULE](https://community.languagetool.org/rule/show/PORTUGUESE_WORD_REPEAT_BEGINNING_RULE?lang=pt)

- Two sentences in a row begin with the same adverb. 
- Consider rephrasing the phrase or use a dictionary to find a synonym.
- **Suggestion**: change `E` to `Ou`

<img width="677" alt="image" src="https://user-images.githubusercontent.com/35238611/177468374-5f94614b-23f3-43ef-b3f2-08459fa246ad.png">

2023-09-18 01:27 UTC, jonnathan-ls commented
/done

2023-09-18 01:28 UTC, jonnathan-ls commented
I applied the corrections I requested by contributing to the PR to be able to accept the request

2023-09-18 01:31 UTC, jonnathan-ls approved these changes

2023-09-18 01:34 UTC, merged