Native prototypes
javascript-tutorial/pt.javascript.info pull request #233
Opened 2021-11-01 18:40 UTC by flaviohblima

2021-11-17 21:44 UTC, odsantos requested changes
Hello @flaviohblima,

Here is a review.
Please, feel free to leave me a note where you might disagree.

Thank you,
Osvaldo.

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Por exemplo, quando nós criamos um array `[1, 2, 3]`, a função construtura padrão `new Array()` é usada internamente. Dessa forma, os dados são escritos dentro do novo objeto, e `Array.prototype` se
```suggestion
Por exemplo, quando nós criamos um array `[1, 2, 3]`, a função construtura padrão `new Array()` é usada internamente. Dessa forma, os dados são escritos dentro do novo objeto, e `Array.prototype` se torna no seu protótipo e provê métodos. Isso é bem eficiente em termos de memória.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Pela especificação, todos os protótipos embutidos tem `Object.prototype` no topo. Algumas pessoas dizem que "tudo herda os objetos".
```suggestion
Pela especificação, todos os protótipos embutidos têm `Object.prototype` no topo. Algumas pessoas dizem que "tudo herda de objetos".
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Como vimos antes, `Object.prototype` também tem o método `toString`, mas `Array.prototype` está mais perto na cadeia, então a variante da array é utilizada.
```suggestion
Como vimos antes, `Object.prototype` também tem o método `toString`, mas `Array.prototype` está mais perto na cadeia, então a variante do array é utilizada.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Ferramentas embutidas em navegadores, como o console do desenvolvedor no Chrome, também mostram herança (objetos embutidos podem precisar usar o `console.dir`):
```suggestion
Ferramentas embutidas em navegadores, como o console do desenvolvedor no Chrome, também mostram herança (objetos embutidos podem precisar de usar o `console.dir`):
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Esses objetos são criados invisivelmente para nós e a maioria das engines otimizam esse processo, apesar da especificação descrevê-lo exatamente dessa forma. Os métodos desses objetos também residem
```suggestion
Esses objetos são criados invisivelmente para nós e a maioria dos interpretadores (*engines*) otimizam esse processo, apesar da especificação descrevê-lo exatamente dessa forma. Os métodos desses objetos também residem nos protótipos, disponíveis como `String.prototype`, `Number.prototype` e `Boolean.prototype`.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +O valores especiais `null` e `undefined` se destacam dos outros. Eles não tem objetos que os envolem, então métodos e propriedades não estão disponíveis para eles. Também não existem protótipos corre
```suggestion
O valores especiais `null` e `undefined` se destacam dos outros. Eles não têm objetos que os envolem, então métodos e propriedades não estão disponíveis para eles. Também não existem protótipos correspondentes.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Durante o processo do desenvolvimento, nós podemos ter novas ideias de métodos embutidos que nós gostaríamos de ter, e podemos ficar tentados a adicioná-los nos protótipos nativos. Mas isso é geralme
```suggestion
Durante o processo do desenvolvimento, nós podemos ter novas ideias de métodos embutidos que nós gostaríamos de ter, e podemos ficar tentados a adicioná-los aos protótipos nativos. Mas isso é geralmente uma má ideia.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +**Na programação moderna, existe apenas um caso quando modificar protótipos nativos é aprovado: fazer polyfill (polyfilling).**
```suggestion
**Na programação moderna, existe apenas um caso erm que modificar protótipos nativos é aprovado: fazer polyfill (polyfilling).**
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +*Polyfill* é um termpo para criar um substituto para um método que existe na especificação do JavaScript, mas ainda não tem suporte em alguma engine particular de JavaScript.
```suggestion
*Polyfill* é um termpo para criar um substituto para um método que existe na especificação do JavaScript, mas ainda não tem suporte em algum interpretador particular de JavaScript.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Nesse caso nós podemos implementar e popular o protótipo embutido com ele.
```suggestion
Nesse caso nós podemos implementar e preencher o protótipo embutido com ele.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +  // adiciona no protótipo
```suggestion
  // adiciona ao protótipo
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +    // mas mesmo imperfeito, o polyfill é geralmente considerado bom o suficiente
```suggestion
    // mas mesmo um polyfill imperfeito, é geralmente considerado bom o suficiente
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Por exemplo, se nós estamos fazendo um objeto parecido com um array, nós podemos querer copiar alguns métodos para ele.
```suggestion
Por exemplo, se nós estamos fazendo um objeto parecido com um array, nós podemos querer copiar alguns métodos de array para ele.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Outra possibilidade é herdar configurando `obj.__proto__` para o `Array.prototype`, de forma que todos os métodos de `Array` fiquem automaticamente disponíveis em `obj`.
```suggestion
Outra possibilidade é herdar configurando `obj.__proto__` para `Array.prototype`, de forma que todos os métodos de `Array` fiquem automaticamente disponíveis em `obj`.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +- Tipos primitivos também guardam métodos em protótipos de objetos que os envolvem (como um invólucro): `Number.prototype`, `String.prototype` e `Boolean.prototype`. Apenas `undefined` e `null` que n
```suggestion
- Tipos primitivos também guardam métodos em protótipos de objetos que os envolvem: `Number.prototype`, `String.prototype` e `Boolean.prototype`. Apenas `undefined` e `null` não tem objetos invólucros.
```

2021-11-17 21:44 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +- Protótipos embutidos podem ser modificados ou populados com novos métodos. Mas modificá-los não é recomendado. O único caso aceitável é provavelmente quando nós adicionamos um novo comportamento e
```suggestion
- Protótipos embutidos podem ser modificados ou populados com novos métodos. Mas modificá-los não é recomendado. O único caso aceitável é provavelmente quando nós adicionamos um novo comportamento e ele ainda não tem suporte em algum interpretador (*engine*) de JavaScript.
```

2021-12-10 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=233) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=233) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: flaviohblima<br/>:x: Osvaldo Dias dos Santos<br/><hr/>**Osvaldo Dias dos Santos** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=233) it.</sub>

2022-02-26 23:37 UTC, flaviohblima commented
/done

2022-12-10 22:53 UTC, odsantos requested changes
Hi @flaviohblima , 

There are other sections of this lesson not translated yet, such as 01, and 02.

Plase, feel free to also tell where you disagree.

Thanks, Osvaldo.

2022-12-10 22:53 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Quando `new Object()` é chamado (ou um objeto literal `{...}` é criado), o seu `[[Prototype]]` é configurado para o `Object.prototype` de acordo com a regra que nós discutimos no capítulo anterior:
```suggestion
Quando `new Object()` é invocado (ou um objeto literal `{...}` é criado), o seu `[[Prototype]]` é configurado para o `Object.prototype`, de acordo com a regra que nós discutimos no capítulo anterior:
```

2022-12-10 22:53 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Outros objetos embutidos também trabalham da mesma forma. Até mesmo funções -- elas são objetos de um construtor `Function` embutido, e seus métodos (`call`/`apply` e outros) são obtidos de `Function
```suggestion
Outros objetos embutidos também trabalham da mesma forma. Até mesmo funções -- elas são objetos de um construtor `Function` embutido, e os seus métodos (`call`/`apply`, e outros) são obtidos de `Function.prototype`. Funções também têm o seu próprio `toString`.
```

2022-12-10 22:53 UTC, odsantos commented on 1-js/08-prototypes/03-native-prototypes/article.md
> +Esses objetos são criados invisivelmente para nós e a maioria dos interpretadores (*engines*) otimizam esse processo, apesar da especificação descrevê-lo exatamente dessa forma. Os métodos desses obj
```suggestion
Esses objetos são criados invisivelmente para nós e a maioria dos interpretadores (*engines*) otimizam esse processo, apesar da especificação descrevê-lo exatamente desta forma. Os métodos desses objetos também residem nos protótipos, disponíveis como `String.prototype`, `Number.prototype` e `Boolean.prototype`.
```

2022-12-21 21:36 UTC, odsantos commented
Hi @flaviohblima , 

Still working on this?
Due to the article update, there are conflicts too.

Thanks,
Osvaldo.

2023-09-18 00:48 UTC, jonnathan-ls commented
Olá @flaviohblima, tudo bem?

Conseguiria avaliar as solicitações registradas pelo @odsantos?

Com o prosseguimento e resolução de conflitos, sigo com minha revisão para darmos andamento a este PR

2024-05-14 06:19 UTC, nazarepiedady commented
@Peruibeloko, could you do something about this pull request?

2024-06-01 15:21 UTC, jonnathan-ls commented
> @jonnathan-ls, could you update this pull request?

@nazarepiedady I fixed merge conflict fixes and observations recorded by @odsantos, also added some outstanding translations in the last 2 commtis https://github.com/javascript-tutorial/pt.javascript.info/pull/233/commits/2d40fdddd71e549cbf9ecab33a77460533e1ba7e and https://github.com/javascript-tutorial/pt.javascript.info/pull/233/commits/06ba0db301e6439fb8b738912792453a58d96c3f

2024-08-05 07:22 UTC, nazarepiedady approved these changes
It is time to go ahead with this pull request.

2024-08-05 07:23 UTC, merged