Translates Class basic syntax
javascript-tutorial/pt.javascript.info pull request #248
Opened 2022-08-17 01:35 UTC by thiagocardoso1988

Source: [Class basic syntax](https://github.com/javascript-tutorial/pt.javascript.info/blob/master/1-js/09-classes/01-class)

2022-08-17 01:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=248) before we can accept your contribution.<br/><hr/>**Thiago Cardoso** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=248) it.</sub>

2022-08-25 03:28 UTC, jonnathan-ls requested changes

2022-08-25 03:28 UTC, jonnathan-ls commented on 1-js/09-classes/01-class/article.md
> +1. Primeiro, uma função criada por `class` é rotulada por uma propriedade interna especial `[[IsClassConstructor]]: true`. Portanto, não é exatamente o mesmo que criá-lo manualmente.
**Sugestão de alteração**:

Evitar redundância, basta remover a palavra *exatamente*.

- Alterar `... não é exatamente o mesmo ...` para `... não é o mesmo ...`

<img width="602" alt="image" src="https://user-images.githubusercontent.com/35238611/186564539-cd9eca07-6510-46df-a70c-f80ff4d7e36a.png">

> Regra "Pleonasmo: Criar novas"
>
> https://community.languagetool.org/rule/show/REDUNDANCY_CRIAR?lang=pt

2022-08-25 03:28 UTC, jonnathan-ls commented on 1-js/09-classes/01-class/article.md
> +Podemos até fazer aulas dinamicamente "sob demanda", assim:
**Sugestão de alteração**:

Ficou muito literal a tradução, a palavra `classes` no inglês refere-se ao uso do `class` de forma genérica.

Portanto, alterar a palavra `aulas` por `classes` ou deixar por algo como:

 > Podemos até fazer uma  classe dinamicamente "sob demanda", assim:

2022-08-25 03:28 UTC, jonnathan-ls commented on 1-js/09-classes/01-class/article.md
> +Esses recursos são fáceis de lembrar, pois se assemelham aos de objetos literais.
**Sugestão de alteração**:

- Adicionar vírgula após a palavra `pois`.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/35238611/186566513-861a1855-fa84-44d7-acf0-84588dbccad6.png">

> Regra "Locuções entre vírgulas: portanto, por exemplo, na verdade"
>
> https://community.languagetool.org/rule/show/VERB_COMMA_CONJUNCTION?lang=pt

2022-08-25 03:28 UTC, jonnathan-ls commented on 1-js/09-classes/01-class/article.md
>  ```warn header="Old browsers may need a polyfill"
Traduzir o texto em `header`.

2022-08-25 03:28 UTC, jonnathan-ls commented on 1-js/09-classes/01-class/article.md
> +2. Vincule o método ao objeto, por exemplo. no construtor.
Sugestão de alteração:

Após `por exemplo` deveria ser uma vírgula em vez de ponto.

- Alterar `por exemplo.` por `por exemplo,`

2023-10-15 20:54 UTC, jonnathan-ls commented
Olá @thiagocardoso1988, conseguiria verificar as solicitações de mudanças que registrei?

2023-11-18 21:31 UTC, odsantos commented
@jonnathan-ls I updated the name of this PR and hope to check the changes as soon as possible. Thanks.

2023-12-23 21:21 UTC, jonnathan-ls commented
Considerando o tempo decorrido, eu adicionei as alterações que solicitei https://github.com/javascript-tutorial/pt.javascript.info/pull/248/commits/e3f47157128d51bac4ca30ab05684c1f0e006f73

/done

2023-12-23 21:21 UTC, jonnathan-ls approved these changes

2023-12-23 23:29 UTC, merged