Attributes and properties
javascript-tutorial/pt.javascript.info pull request #403
Opened 2023-07-24 03:39 UTC by denis-rossati

From this [request](https://github.com/javascript-tutorial/pt.javascript.info/issues/1#issuecomment-1086159388)

2023-07-24 03:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=403) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=403) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=403) it.</sub>

2023-07-28 14:51 UTC, renatocfrancisco reviewed
https://github.com/javascript-tutorial/pt.javascript.info/blob/4eae541925242050887a33bb361eb151d477006b/2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md?plain=1#L2
It could be `...todas as referências externas.`

https://github.com/javascript-tutorial/pt.javascript.info/blob/4eae541925242050887a33bb361eb151d477006b/2-ui/1-document/06-dom-attributes-and-properties/article.md?plain=1#L3
Could be `Quando o navegador...`

https://github.com/javascript-tutorial/pt.javascript.info/blob/4eae541925242050887a33bb361eb151d477006b/2-ui/1-document/06-dom-attributes-and-properties/article.md?plain=1#L54
There is a `{"type": {"type": "text"}}` instead of `reconhece`

https://github.com/javascript-tutorial/pt.javascript.info/blob/4eae541925242050887a33bb361eb151d477006b/2-ui/1-document/06-dom-attributes-and-properties/article.md?plain=1#L139
`assinalar` can be `atribuir`

Besides that, LGTM! 👍🏻

2023-07-30 15:15 UTC, jonnathan-ls requested changes
Olá @denis-rossati, 

Subi um `commit` em seu PR com ajustes simples, não faria sentido eu ficar pontuando pouca coisa se posso ajustar direto :)

Se alguma mudança que fiz não fizer sentido, sinta-se livre para modificar.

Registrei apenas algumas observações como substituição de trechos mais completos para dar sentido melhor ao artigo, veja se faz sentidos as sugestões, por favor: https://github.com/javascript-tutorial/pt.javascript.info/pull/403/commits/f182d28d6b9c6d9372f738b4e8ad4adfd4636796

**Observação**: não esqueça de realizar um `pull` de sua `branch` para atualizar o trabalho quando for realizar algum ajuste.

2023-07-30 15:34 UTC, jonnathan-ls commented
> [renatocfrancisco](https://github.com/renatocfrancisco) reviewed [2 days ago](https://github.com/javascript-tutorial/pt.javascript.info/pull/403#pullrequestreview-1552288452)

Olá Renato, boas observações, como adicionei uma revisão neste PR, acabei corrigindo coisas simples, a qual cobriram as reviews que pontuou, como pode ser visto em https://github.com/javascript-tutorial/pt.javascript.info/pull/403/commits/f182d28d6b9c6d9372f738b4e8ad4adfd4636796

Em relação a revisão, me parece que o bot do repositório não considerou suas observações:

> Geralmente no PR é registrado a revisão realizada e quem a registrou
![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/85dde6b2-0c27-4171-ac85-0d708ff3ac61)

Talvez por que precisa realizar procedimentos associados a contribuição deste repositório

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/a6098429-554e-4ed4-9d69-0440002c97a8)

**De qualquer modo**, para contribuir com revisões neste repositório, sugiro que registre a intenção na issue https://github.com/javascript-tutorial/pt.javascript.info/issues/1 a qual contém orientações gerais, para que o `owner` do repositório possa saber e avaliar a inclusão de contribuição de revisor.

2023-10-15 20:51 UTC, jonnathan-ls commented
Olá @denis-rossati, conseguiu verificar as solicitações de mudanças que registrei em [#pullrequestreview-1553650939](https://github.com/javascript-tutorial/pt.javascript.info/pull/403#pullrequestreview-1553650939)?

2023-11-18 21:38 UTC, odsantos commented
@jonnathan-ls I would suggest that a person would first contribute with translations before asking to me a maintainer. Thanks.

2023-11-18 21:44 UTC, jonnathan-ls commented
@odsantos , Perfectly ❤️, it is actually more relevant, even for evaluating contributions to the repository.

2023-12-23 21:09 UTC, jonnathan-ls commented
Considerando o tempo decorrido, eu mesmo adicionei o ajuste das sugestões https://github.com/javascript-tutorial/pt.javascript.info/pull/403/commits/3484cc3f98d71d0dbe980865b8dfd2a9fc13dabf

/done

2023-12-23 21:09 UTC, jonnathan-ls approved these changes

2023-12-23 23:30 UTC, merged