Updates Object references and copying article
javascript-tutorial/pt.javascript.info pull request #408
Opened 2023-11-29 15:57 UTC by danilolmc

2023-12-10 18:43 UTC, jonnathan-ls requested changes
Olá @danilolmc, 

Eu tentei empurrar para sua `branch` algumas alterações simples de gramática que acabei fazendo enquanto realizava a revisão deste PR.

Porém, seu fork/user deve estar protegido para receber commits de outros usuários, acabei recebendo error de `permission denied`:

>  ! [remote rejected]     pr/408 -> update-pt-object-copy (permission denied)
> error: failed to push some refs to 'https://github.com/danilolmc/pt.javascript.info.git'

Nesse sentido, registro abaixo as alterações que eu ia adicionar ao seu PR, poderia verificar as solicitações a seguir?

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/1e7364ac-0878-4229-ae1b-e46128903d2a)

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/b1540c4a-441f-473b-8a79-288110bcc223)

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +E aqui é como ela realmente está armazenada na memória
#### Sugestão: [ter em conta a colocação do advérbio.](https://community.languagetool.org/rule/show/COLOCA%C3%87%C3%83O_ADV%C3%89RBIO?lang=pt-BR)

```diff
- E aqui é como ela realmente está armazenada na memória
+ E aqui é como ela está realmente armazenada na memória
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +**Quando uma variável de objeto é copiada, a referência é copiada, mas o próprio objeto não é diplicado**
#### Correção: 

- Alterar `diplicado` por `duplicado`

```diff
- ... não é diplicado**
+ ... não é duplicado**
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +É como se tivéssemos uma armário com duas chaves e usado uma delas (`admin`) para abri-lo e fazer alterações. Então, se depois usarmos a outra chave (`user`), ainda estaremos abrindo o mesmo armário
#### Correção: concordância de gênero 

- Alterar `uma armário` por `um armário`

```diff
- É como se tivéssemos uma armário ...
+ É como se tivéssemos um armário ...
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +// vamos copiar todas as propriedades de usuario para ele
#### Correção: sintaxe

- Alterar `usuario` por `usuário`

```diff
- ... usuario para ele
+ ... usuário para ele
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +A syntax é:
#### Sugestão: tradução

- Alterar `syntax` por `sintaxe`

```diff
- A syntax é:
+ A sintaxe é:
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +A chamada `structuredClone(object)` clone o `object` como todas as propriedades aninhadas.
#### Sugestão: concordância

- Alterar `clone` por `clona`
- Alterar `como` por `com`

```diff
- A chamada ... clone o `object` como ...
+ A chamada ... clona o `object` com ...
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +alert( user.sizes === clone.sizes ); // false, objectos diferentes
#### Sugestão: tradução

- Alterar `objectos` por `objetos`

```diff
- ... objectos diferentes
+ ... objetos diferentes
```

2023-12-10 18:43 UTC, jonnathan-ls commented on 1-js/04-object-basics/02-object-copy/article.md
> +Como você pode ver `clone.me` faz referência a `clone`, não a `user`! , Então a referência circular foi clonada corretamente também.
#### Sugestão: 

- Remover pontuação desnecessária: virgula

```diff
- ... `user`! , Então ...
+ ... `user`! Então ...
```

2023-12-20 02:40 UTC, danilolmc commented
/done

2023-12-20 13:59 UTC, merged

2023-12-23 20:53 UTC, jonnathan-ls commented
@nazarepiedady como fez o merge, entendo que adicionou sua revisão como aprovada como a segunda revisora, creio ser válido deixar registrado que o PR esta aprovado, conforme seção abaixo

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/8b00754a-2013-4ce5-be93-1489d91b5218)

Após o merge não consigo realizar a atualização, mas deixo a observação para próximos PRs

A aprovação de dois revisores corrobora com a orientação deixa pelo Ilkan

![image](https://github.com/javascript-tutorial/pt.javascript.info/assets/35238611/34e37cbb-7adf-4289-8647-09bec70cc468)

2023-12-23 23:36 UTC, nazarepiedady commented
@jonnathan-ls, entendo, considerarei este ponto da próxima vez que precisar combinar as modificações enviadas ao repositório principal. Na primeira leitura que tinha feito pareceu-me bem o trabalho feito, por esta razão fiz a combinação, não volta acontecer.