Async iteration and generators
javascript-tutorial/pt.javascript.info pull request #418
Opened 2024-01-08 15:21 UTC by danilolmc

2024-02-28 08:47 UTC, nazarepiedady requested changes
@danilolmc, could you update your pull request?

2024-02-28 08:47 UTC, nazarepiedady commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +## Relembrando iteráveis
It must not use the gerund because the original text does not refer to this, so we should translate as **Relembrar os iteráveis**.

2024-02-28 08:48 UTC, nazarepiedady commented
@Peruibeloko, could you do the honours?

2024-02-28 12:34 UTC, Peruibeloko requested changes
Além dos comentários que deixei, senti falta de conectores como artigos em diversos pontos, como "o `await`", "o - `async`", etc. mas não acho que sejam problemas grandes demais para prejudicar a compreensão do texto

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Se algo não estiver claro, consulte o capítulo  [](info:iterable), que fornece todos os detalhes sobre iteráveis regulares.
Acho que "tradicionais" ou "comuns" funciona melhor aqui no lugar de "regulares", já que no inglês _regular_ nessa passagem tem a conotação de algo mundano, comum, ao invés de regrado e estruturado

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +3. Para iterar sobre esse objeto, devemos usar um lopp `for await (let item of iterable)`.
lopp → loop

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Recursos que exigem iteradores regulares, síncronos, não funcionam com iteradores assíncronos.
regulares → comuns ou tradicionais

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Para geradores assíncrono, o método `generator.next()` é assíncrono, ele retorna promises.
```suggestion
Para geradores assíncronos, o método `generator.next()` é assíncrono, ele retorna promises. 
```
Concordância

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Geradores regulares podem ser usados ​​como `Symbol.iterator` para tornar o código de iteração mais curto.
regulares → comuns ou tradicionais

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Por exemplo, GitHub nos permite recuperar commits da mesma maneira paginados:
```suggestion
Por exemplo, GitHub nos permite recuperar commits da mesma maneira paginada:
```
Concordância

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +1. Usamos o o método do navegador [fetch](info:fetch) para baixar os commits.
```suggestion
1. Usamos o método [fetch](info:fetch) do navegador para baixar os commits.
```

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Isso é apenas o que queremos.
```suggestion
Isso é exatamente o que queremos.
```

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Iteradores regulares e geradores funcionam bem com dados que não levam tempo para serem gerados.
regulares → comuns ou tradicionais

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Diferenças de sintaxe entre iteradores assíncronos e regulares:
regulares → comuns ou tradicionais

2024-02-28 12:34 UTC, Peruibeloko commented on 1-js/12-generators-iterators/2-async-iterators-generators/article.md
> +Diferenças de sintaxe entre geradores assíncronos e regulares:
regulares → comuns ou tradicionais

2024-03-04 21:06 UTC, danilolmc commented
/done

2024-03-06 03:10 UTC, Peruibeloko approved these changes

2024-03-06 07:30 UTC, nazarepiedady approved these changes
I approve it.

2024-03-06 07:32 UTC, merged