BigInt
javascript-tutorial/pt.javascript.info pull request #430
Opened 2024-02-06 20:23 UTC by danilolmc

2024-02-06 20:36 UTC, nazarepiedady reviewed
@danilolmc, what do you think about consider the idea about translating the word `bigint` in the article content as `número inteiro grande` or `inteiro grande` or `inteiro maior`?

@Peruibeloko, @jonnathan-ls, @odsantos, what do you think about the suggestion I did?

2024-02-06 21:27 UTC, Peruibeloko commented
@nazarepiedady I'd keep it as BigInt, and the only change I'd suggest is to capitalize it, since we're dealing with the actual object's name, much like we shouldn't translate `Promise` to `Promessa` for example :)

2024-02-06 21:39 UTC, danilolmc commented
I agree with @Peruibeloko, since BigInt is just like Promise and a data type itself.

@Peruibeloko do you mean capitalize every bigint word in the article? I just let some bigint words as it was already capitalized.

2024-02-06 22:27 UTC, Peruibeloko commented
@danilolmc Yes, that would be the case. Just a suggestion, of course.

2024-02-06 22:45 UTC, danilolmc commented
Ok, no problem, I'm going to capitalize them!

2024-02-07 12:53 UTC, nazarepiedady commented
> @nazarepiedady I'd keep it as BigInt, and the only change I'd suggest is to capitalize it, since we're dealing with the actual object's name, much like we shouldn't translate `Promise` to `Promessa` for example :)

@Peruibeloko, I was talking about to translate the usage of the word **bigint** where it is not reference the data type.

2024-02-07 13:07 UTC, Peruibeloko commented
@nazarepiedady the problem is that `bigint` always refers to the data type

2024-02-07 13:16 UTC, Peruibeloko requested changes
Solicitei algumas mudanças, deve ser rápido

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +BigInt é um tipo numérico especial que oferece suporte para inteiros de comprimento arbitrário.
Eu usaria o termo "tamanho" ao invés de comprimento

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +`BigInt` pode ser usado principalmente como um número regular, por exemplo:
O termo "Regular" em inglês é melhor traduzido para "comum" nesses contextos

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
Regular -> Comum

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +Devemos convertê-los explicitamente se necessário: usando `BigInt()` ou `Number()`, assim:
Eu costumo remover marcações de `:` que eu considero desnecessárias ou gramaticalmente incorretas em PT. Aqui por exemplo, eu usaria "[...] explicitamente se necessário, usando [...]"

A vírgula oferece uma continuidade melhor ao texto

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +````smart header="O operador unário mais não é suportado em bigints"
A ordem no português é invertida, fica "mais unário", já que "unário" é um adjetivo de "mais"

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +Fazer polyfill para bigints é complicado. A razão é que muitos operadores JavaScript, como `+`, `-` e assim por diante se comportam de maneira diferente com bigints em comparação com números regulare
Polyfill na tradução se torna um substantivo, ficaria então "Fazer um polyfill" ou "Fazer polyfills", eu prefiro o primeiro

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +Embora, o caminho inverso é proposto pelos desenvolvedores da biblioteca [JSBI](https://github.com/GoogleChromeLabs/jsbi).
"Embora" me parece meio desconexo aqui, que tal "Apesar disso"?

2024-02-07 13:16 UTC, Peruibeloko commented on 1-js/99-js-misc/05-bigint/article.md
> +- [Documentação da MDN sobre BigInt](mdn:/JavaScript/Reference/Global_Objects/BigInt).
Acho que vale usar o link para a MDN em PT

2024-02-07 15:16 UTC, danilolmc commented
/done

2024-02-07 16:45 UTC, Peruibeloko approved these changes

2024-02-07 22:56 UTC, odsantos commented
> I agree with @Peruibeloko, since BigInt is just like Promise and the data type name itself.
> 
> @Peruibeloko do you mean capitalize every bigint word in the article? I just let some bigint words as it was already capitalized.

Seems good, as the Portuguese 'mdn' link, and other accepted suggestions here.

2024-02-11 18:01 UTC, nazarepiedady approved these changes

2024-02-11 18:03 UTC, merged