alert prompt confirm
javascript-tutorial/pt.javascript.info pull request #46
Opened 2019-08-25 18:34 UTC by EvertonCosmo

Translating alert prompt confirm

2019-08-25 18:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=46) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=46) it.</sub>

2019-08-30 14:38 UTC, luizclr commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> + mostrará uma mensagem até o usuário pressionar  "OK".
This phrase should start with capital letter, and I think you should set the verb on present: "Mostra uma mensagem".

2019-08-31 11:27 UTC, EvertonCosmo commented
/done

2019-09-16 12:42 UTC, EvertonCosmo commented
/done

2019-11-04 13:21 UTC, EvertonCosmo commented
/done

2019-12-29 19:10 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Esse é o preço da simplicidade. Existem outras duas maneiras de mostrar janelas mais agradáveis e interações mais ricas com os visitantes, mas se "sinos e assobios" não importam muito, esses métodos
- "<s>Esse</s> Este é o preço..."
(though correct, would you kindly change to that word?)
- "Existem <s>duas</s> outras maneiras..."

2020-02-18 11:16 UTC, EvertonCosmo commented
changes requested done

2020-02-18 11:16 UTC, EvertonCosmo commented
/done

2020-03-30 12:12 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Mas ainda estaremos usando o navegador como nosso ambiente de demostração, portanto devemos conhecer pelo menos algumas das suas funções de interface com o usuário. Neste capítulo, iremos nos familia
- "... ambiente de <s>demostração</s> demonstração,"

2020-03-30 12:15 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +A mini-janela é chamada de modal  *window*. A palavra "modal" significa que o visitante não pode interagir com o resto da página, pressionar outros botões, etc. até que ele tenha lidado com a janela.
- '... chamada de <s>modal  \*window\*</s> \*modal window\*.'

2020-03-30 12:23 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Mostra uma janela modal com uma mensagem de texto,um campo de entrada para o visitante, e os botões OK/CANCEL
- "... mensagem de <s>texto,um</s> texto, um campo ..."

2020-03-30 12:33 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
>  ````warn header="In IE: always supply a `default`"
- Would you please translate here?
( but not 'IE', and \`default\` )

2020-03-30 12:34 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +: mostra uma mensagem pedindo para o usuário inserir texto. Ele retorna o texto ou, se CANCEL ou `key:Esc` for clicado, `null`.
- "<s>Ele</s> Ela retorna o texto ou,"

2020-03-30 12:36 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +: mostra uma mensagem e espera que o usuário pressione  "OK" ou "CANCEL". Ele retorna `true` para OK e `false` para CANCEL/`key:Esc`.
- "<s>Ele</s> Ela retorna \`true\` ..."

2020-03-30 12:37 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Todos esse métodos são modais: eles pausam a execução do script e não permitem o visitante interagir com o resto da página até que a janela seja descartada.
- "... não permitem <s>-o-</s> ao visitante ..."

2020-03-30 12:40 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Este é o preço da simplicidade. Existem outras maneiras de mostrar janelas mais agradáveis e interações mais ricas com os visitantes, mas se "sinos e assobios" não importam muito, esses métodos funci
- "... mostrar janelas mais agradáveis e interações mais ricas <s>com os</s> aos visitantes,"

2020-03-30 12:41 UTC, odsantos commented on 1-js/02-first-steps/09-alert-prompt-confirm/article.md
> +Todos esse métodos são modais: eles pausam a execução do script e não permitem o visitante interagir com o resto da página até que a janela seja descartada.
- "... não permitem <s>-o-</s> ao visitante ..."

2020-04-24 23:34 UTC, EvertonCosmo commented
/done

2020-05-16 18:06 UTC, EvertonCosmo commented
/done

2020-05-17 16:48 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
> +Crie uma página web que solicite um nome e o exiba [demo]
Please, keep the new line before "[demo]"

2020-05-17 16:54 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Esta parte do tutorial tem como objetivo cobrir o JavaScript "como é ", sem ajustes específicos de ambiente.
Could you update your translation with respect to the english version? https://github.com/javascript-tutorial/en.javascript.info/blob/master/1-js/02-first-steps/06-alert-prompt-confirm/article.md some parts have changed. Thank you!

2020-05-20 21:05 UTC, EvertonCosmo commented
/done

2020-05-23 16:04 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
> +Crie uma página web que solicite um nome e o exiba
missing endpoint

2020-05-23 16:05 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
> +let name = prompt("Qual o seu nome ?", "");
please remove space before ?

2020-05-23 16:05 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
> +    let name = prompt("Qual o seu nome ?", "");
same thing, please remove space before ?

2020-05-23 16:05 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Este já vimos. Ele mostra uma mensagem e aguarda o usuário pressionar "OK"
missing endpoint

2020-05-23 16:06 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Por exemplo :
remove space before :

2020-05-23 16:06 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +A mini-janela com a mensagem é chamada de _modal window_. A palavra "modal" significa que o visitante não pode interagir com o resto da página, pressionar outros botões, etc. até que ele tenha lidado
missing endpoint

2020-05-23 16:07 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +A mini-janela com a mensagem é chamada de _modal window_. A palavra "modal" significa que o visitante não pode interagir com o resto da página, pressionar outros botões, etc. até que ele tenha lidado
please use * to enclose "modal window", not _

2020-05-23 16:08 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +A mini-janela com a mensagem é chamada de _modal window_. A palavra "modal" significa que o visitante não pode interagir com o resto da página, pressionar outros botões, etc. até que ele tenha lidado
minor typo, after etc use a comma

2020-05-23 16:08 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +A função `prompt` aceita dois argumentos
missing :

2020-05-23 16:08 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Mostra uma janela modal com uma mensagem de texto, um campo de entrada para o visitante, e os botões OK/CANCEL
missing endpoint. Please use Cancel instead of CANCEL.

2020-05-23 16:11 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Por exemplo:
keep a new empty line in between those lines as in the original it makes it easier to merge in the future.

2020-05-23 16:11 UTC, kiniggit commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +let isBoss = confirm("Você é o chefe ?");
remove space before ?

2020-05-23 16:13 UTC, kiniggit commented
Thank you for updating the translation! I've requested somer minor changes. Cheers!

2020-05-24 17:59 UTC, EvertonCosmo commented
/done

2020-11-25 20:32 UTC, odsantos commented
Hi @EvertonCosmo I see @kiniggit asked you for changes.
If you still have this in progress, could you also resolve the conflicts?
If you may feel unable to continue, could you please also leave a note?
Thank you.

2020-12-27 20:06 UTC, odsantos commented
> Hi @EvertonCosmo I see @kiniggit asked you for changes.
> If you still have this in progress, could you also resolve the conflicts?
> If you may feel unable to continue, could you please also leave a note?
> Thank you.

Hi @EvertonCosmo , actually there seems not to exist pending requested changes here, but only conflicts. Thank you.

2020-12-29 16:47 UTC, EvertonCosmo commented
Hi @odsantos, i will make the new changes asap

2020-12-29 19:26 UTC, odsantos commented
Hi @EvertonCosmo   thank you. Please,  you may also let me know if temporarily you can't and I may try it.

2020-12-29 21:52 UTC, EvertonCosmo commented
> Hi @EvertonCosmo thank you. Please, you may also let me know if temporarily you can't and I may try it.

Okay

2021-01-06 23:32 UTC, EvertonCosmo commented
/done

2021-01-06 23:44 UTC, EvertonCosmo commented
@odsantos updated !

2021-01-07 17:48 UTC, odsantos requested changes
Hi @EvertonCosmo ,
Here is a review. Please feel free to comment on it.
Thank you.

2021-01-07 17:48 UTC, odsantos commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +Este já vimos. Ele mostra uma mensagem e aguarda o usuário pressionar "OK".
```suggestion
Esta já vimos. Ela mostra uma mensagem e aguarda o usuário pressionar "OK".
```

2021-01-07 17:48 UTC, odsantos commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +```smart header="Os colchetes na sintaxe `[...]`" Os colchetes ao redor de `default` na sintaxe acima denota que o parâmetro como opcional, não é obrigatório.
```suggestion
```smart header="Os colchetes na sintaxe `[...]`"
Os colchetes ao redor de `default` na sintaxe acima denotam que o parâmetro é opcional, não é obrigatório.
```

2021-01-07 17:48 UTC, odsantos commented on 1-js/02-first-steps/06-alert-prompt-confirm/article.md
> +````warn header="No IE: sempre forneça um `default`" O segundo parâmetro é opcional, mas se não o fornecermos, o Internet Explorer irá inserir o texto `"undefined"` no prompt.
```suggestion
````warn header="No IE: sempre forneça um `default`"
O segundo parâmetro é opcional, mas se não o fornecermos, o Internet Explorer irá inserir o texto `"undefined"` no prompt.
```

2021-01-11 23:32 UTC, EvertonCosmo commented
/done

2021-01-12 18:46 UTC, odsantos approved these changes
Hi @EvertonCosmo , 
Thank you.

2021-01-13 19:44 UTC, merged