Logical operators
javascript-tutorial/pt.javascript.info pull request #56
Opened 2019-09-19 13:13 UTC by Mr-Saxobeat

Translate article, tasks and solutions.

2019-09-19 13:15 UTC, Mr-Saxobeat commented
> Error: the article already has PR number in the Progress Issue #1, it's 55 ⁉️

@iliakan What I should do? I've already closed the #55 because I forgot to translate the tasks that before.

2019-09-19 14:01 UTC, Mr-Saxobeat commented
I'm sorry, I didn't know that I should commit to the older pull request #55 .

2019-12-17 22:03 UTC, odsantos commented on 1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
> +Crie duas variações: a primeira usando NÃO `!`, e uma segunda -- sem ele.
- "Crie duas <s>variações</s> variantes: ..."

2019-12-17 22:24 UTC, odsantos commented on 1-js/02-first-steps/11-logical-operators/article.md
>      let currentUser = null;
- "Nós podemos usar <s>OU</s> OR `||`:"

2020-05-15 19:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=56) it.</sub>

2020-11-25 20:48 UTC, odsantos commented
Hi @Mr-Saxobeat you're still on this?
If so, could please also  resolve the conflicts?
Thank you.

2021-07-23 17:45 UTC, herbertpdl commented
Hello @odsantos, I would like to collaborate. I saw that this topic is stopped from a long time.
Could I start for this one? 

Thank you!

2021-07-23 19:59 UTC, odsantos commented
Hi @herbertpdl we'd appreciate it if you could translate Thank you.

2022-07-16 22:07 UTC, jonnathan-ls commented
This PR has been open for a long time and there has been no progress on the requested review.

Before evaluating what will be done with this demand:

@Mr-Saxobeat: are you still interested in continuing the translation? If so, please check the notes recorded in the requested code review by @odsantos, after correction, I will carry out my review.

@herbertpdl: if MrSaxobeat, not interested or not responding, would you like to do a translation?

2023-03-11 22:48 UTC, jonnathan-ls requested changes
Segue minha revisão!

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Embora eles sejam chamados de "lógicos", podem ser aplicados a valores de qualquer tipo, não apenas a boolean. Seus resultados também podem ser de qualquer tipo.
```suggestion
Embora eles são denominados como "lógicos", podem ser aplicados a valores de qualquer tipo, não apenas ao tipo `boolean`. Seus resultados também podem ser de qualquer tipo.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Em programação clássica, o operador OU é mencionado para manipular apenas valores booleanos. Se qualquer um dos seus argumentos for `true`, ele retorna `true`, se não, retorna `false`.
Complementando a sugestão do @odsantos em [", o operador lógico OU é <s>mencionado</s> utilizado para manipular ..."](https://github.com/javascript-tutorial/pt.javascript.info/pull/56/files#r358993776)

```suggestion
Em programação clássica, o operador OU é utilizado para manipular apenas valores do tipo `boolean`. Se qualquer um dos seus argumentos for `true`, ele retorna `true`, se não, retorna `false`.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Em JavaScript, este operador é um pouco mais útil e poderoso. Mas primeiro, vamos ver o que acontece com valores booleanos.
```suggestion
Em JavaScript, este operador é um pouco mais útil e poderoso. Mas primeiro, vamos ver o que acontece com valores do tipo `boolean`.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Se um operando não é um boolean, ele é convertido em um boolean para ser avaliado.
```suggestion
Se um operando não é um `boolean`, ele é convertido em um `boolean` para ser avaliado.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Em outras palavras, uma cadeia de OU `"||"` retorna o primeiro valor verdadeiro ou o último se nenhum `true` for encontrado.
```suggestion
Em outras palavras, uma cadeia de OU `"||"`, retorna o primeiro valor verdadeiro ou o último se nenhum `true` for encontrado.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Operandos podem não ser apenas valores, mas operações arbitrárias. OU interpreta e testa elas da esquerda para a direita. A avaliação é interrompida quando um valor verdadeiro é encontrado e este
Complementando a sugestão

```suggestion
    Operandos podem não ser apenas valores, mas operações arbitrárias. `OR` interpreta e testa elas da esquerda para a direita. A avaliação é interrompida quando um valor verdadeiro é encontrado e este valor é retornado. Este processo é denominado como "avaliação em curto-circuito", pois vai o mais curto possível da esquerda para a direita.
```

2023-03-11 22:48 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Como podemos ver, esse caso é como "uma maneira mais curta de se usar `if`". O primeiro operando é convertido para boolean. Se for false, o segundo operando é avaliado.
Complementando a sugestão do @odsantos em [Dec 17, 2019](https://github.com/javascript-tutorial/pt.javascript.info/pull/56/files#r359009516)

```suggestion
    Como podemos ver, este caso é como "uma maneira mais curta de se usar `if`". O primeiro operando é convertido para o tipo `boolean`. Se for `false`, o segundo operando é avaliado.
```

2023-03-11 22:54 UTC, jonnathan-ls commented
@odsantos adicionei minha revisão também.

Considerando que este PR e bastante antigo e como não tivemos retorno do @Mr-Saxobeat, pensei em utilizar a tradução realizada, corrigir as sugestões que solicitamos e realizar o `commit` diretamente neste PR, o que acha ? 

> Tudo bem realizarmos desta forma ?

2023-03-12 23:16 UTC, odsantos commented
@jonnathan-ls I agree. Probably we could resolve the conflicts, revise each other, or have another maintainer joined to this PR, and have it merged when at least two maintainers see the translation ready for that.

2023-03-27 00:46 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
O trecho de código está correto @odsantos.

2023-03-27 00:50 UTC, jonnathan-ls commented on 1-js/02-first-steps/11-logical-operators/article.md
O trecho de código esta correto.

2023-04-17 00:27 UTC, jonnathan-ls commented
> English

Considering that this PR is abandoned and the branch that the user used in the merge creation is no longer available so that it would be possible to contribute directly, a new PR #401 was opened replicating the existing translation in this PR with the corrections of the revision suggestions presented.

Therefore, we are closing this PR.

> Portuguese

Considerando que este PR está abandonado e a branch que o usuário utilizou na criação do merge não está mais disponível para que fosse possível contribuir diretamente, foi aberto um novo PR #401  replicando a tradução existente neste PR com as correções das sugestões de revisão apresentadas

Portanto, estamos dando como encerrado este PR.

2023-04-17 00:29 UTC, closed without merging