Loops: while and for
javascript-tutorial/pt.javascript.info pull request #77
Opened 2019-10-21 20:54 UTC by alvar-o

I'm sorry for the mess in the commits. I got my credentials right and here's the work on the chapter "Loops: while and for".

2019-10-21 20:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=77) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/pt.javascript.info?pullRequest=77) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: alvar-o<br/>:x: Álvaro Antonio<br/><hr/>**Álvaro Antonio** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/pt.javascript.info?pullRequest=77) it.</sub>

2019-10-21 23:59 UTC, odsantos commented
@alvar-o Hi, I'll have to take a look at the bot messages first. Thanks.

2019-10-22 13:17 UTC, alvar-o commented
> @alvar-o Hi, I'll have to take a look at the bot messages first. Thanks.

I had an issue with the credentials configured in my git, I thought I had solved it but my previous commits still show with the wrong credentials. The only way to work this out seems to be to delete my fork and start a new one, then make a new pull request. Let me know if this is needed! :)

2019-12-16 19:42 UTC, odsantos commented
Hi @alvar-o, if you can delete the fork, make a new one and a new PR with only one file I would appreciate.

You might be considering to clone your fork to your computer.

If you already have  a cloned fork in your computer, please delete that folder before cloning your new fork. But, before deleting anything make a backup copy of your translation (save it on a file) for an easy copy/paste later. 

On the PR, do not also forget to accept the license.

Thanks.

2020-11-27 02:09 UTC, odsantos commented
Hi @alvar-o is this still in progress?
If so, could you remove the conflicts, otherwise would you please inform of your unavailability?
Thank you.

2021-07-23 18:00 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
> +Este exercício demonstra como formas posfixadas/prefixadas podem levar a resultados distintos quando utilizadas em comparações.
```suggestion
Este exercício demonstra como formas pós-fixadas/prefixadas podem levar a resultados distintos quando utilizadas em comparações.
```

2021-07-23 18:02 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
> +    O primeiro valor é novamente `i = 1`. A forma posfixada `i++`incrementa `i` e em seguida retorna o valor *antigo*, então a comparação `i++ < 5` utilizará `i = 0` (diferente de `++i < 5`).
```suggestion
    O primeiro valor é novamente `i = 1`. A forma pós-fixada `i++`incrementa `i` e em seguida retorna o valor *antigo*, então a comparação `i++ < 5` utilizará `i = 0` (diferente de `++i < 5`).
```

2021-07-23 18:03 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/2-which-value-while/solution.md
> +    Vamos parar em `i = 4`. A forma prefixada `++i` iria incrementar e utilizar `5` na comparação. Mas aqui temos a forma posfixada `i++`. Ela incrementa `i` para `5`, mas retorna o valor antigo. Por
```suggestion
    Vamos parar em `i = 4`. A forma prefixada `++i` iria incrementar e utilizar `5` na comparação. Mas aqui temos a forma pós-fixada `i++`. Ela incrementa `i` para `5`, mas retorna o valor antigo. Portanto a comparação é, na verdade, `while(4 < 5)` -- verdadeira, e o controle passa para `alert`.
```

2021-07-23 18:30 UTC, herbertpdl requested changes
Just some points.

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
> +1. Executar `i = 0` uma vez antes de tudo (begin).
```suggestion
1. Executa `i = 0` uma vez antes de tudo (begin).
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
> +2. Verificar a condição `i < 5`.
```suggestion
2. Verifica a condição `i < 5`.
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/3-which-value-for/solution.md
> +3. Caso verdadeira (`true`), executar o corpo do loop `alert(i)`, e em seguida `i++`.
```suggestion
3. Caso verdadeira (`true`), executa o corpo do loop `alert(i)`, e em seguida `i++`.
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/3-which-value-for/task.md
> +1. A forma posfixada:
```suggestion
1. A forma pós-fixada:
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/6-repeat-until-correct/task.md
> +Aqui podemos assumir que o usuário só digita números. Não é preciso implementar um tratamento especial para inputs não-numéricos neste exercício.
```suggestion
Aqui podemos assumir que o usuário digita apenas números. Então, não é preciso implementar um tratamento especial para inputs não-numéricos neste exercício.
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/7-list-primes/solution.md
> +Há muitos algotimos para esta tarefa.
```suggestion
Há muitos algoritmos para esta tarefa.
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +| part     |            |                                                                                |
```suggestion
| parte    |            |                                                                                |
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +→ (se condição verdadeira → executar corpo e executar etapa)
```suggestion
Executa o início
→ (se condição verdadeira → executa o corpo e executa a etapa)
→ (se condição verdadeira → executa o corpo e executa a etapa)
→ (se condição verdadeira → executa o corpo e executa a etapa)
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +// executar condição
```suggestion
// executa o início
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +// se condição verdadeira → executar corpo e executar etapa
```suggestion
// se condição verdadeira → executa o corpo e executa a etapa
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +// se condição verdadeira → executar corpo e executar etapa
```suggestion
// se condição verdadeira → executa o corpo e executa a etapa
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +// se condição verdadeira → executar corpo e executar etapa
```suggestion
// se condição verdadeira → executa o corpo e executa a etapa
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +// ...encerrar, pois agora i == 3
```suggestion
// ...encerra, pois agora i == 3
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +  // se verdadeiro, pular o restante do corpo
```suggestion
  // se verdadeiro, pula o restante do corpo
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +    // se retornar um string vazio ou cancelar, quebrar ambos os loops
```suggestion
    // se retornar um string vazio ou cancelar, quebra ambos os loops
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +    // fazer algo com input...
```suggestion
    // faz algo com input...
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +Para fazer um loop "infinito", geralmente se utiliza a construção `white(true)`. Este loop, como qualquer outro, pode ser interrompido com o comando `break`.
```suggestion
Para fazer um loop "infinito", geralmente se utiliza a construção `while(true)`. Este loop, como qualquer outro, pode ser interrompido com o comando `break`.
```

2021-07-23 18:30 UTC, herbertpdl commented on 1-js/02-first-steps/12-while-for/article.md
> +`break/continue` suportam labels antes do loop. Um label é a única maneira de fazer  um `break/continue` escapar um loop aninhado e ir para o loop de fora.
```suggestion
`break/continue` suportam labels antes do loop. Um label é a única maneira de fazer um `break/continue` escapar um loop aninhado e ir para o loop de fora.
```

2021-07-23 19:54 UTC, odsantos commented
Hello @herbertpdl , only maintainers should review the pull requests on this repository.
It even has conflicts, so it is expected to be outdated.

2022-12-14 22:15 UTC, odsantos commented
Hello @herbertpdl ,

It seems you no longer are working on this.

I am afraid I am releasing this lesson for another person within a week.

Thanks,
Osvaldo.

2025-11-25 09:35 UTC, nazarepiedady commented
@gabifs

2025-12-06 18:48 UTC, gabifs commented
@nazarepiedady I am not being able to resolve theses conflicts, so I will close the PR

2025-12-06 18:48 UTC, closed without merging